#!/bin/bash
SQL=$(cat <<HERE
CREATE USER udba SUPERUSER PASSWORD '${DB_FORMATION_DBA_PASSWORD}';
CREATE USER uclient PASSWORD '${DB_FORMATION_CLIENT_PASSWORD}';
CREATE USER ustaff PASSWORD '${DB_FORMATION_STAFF_PASSWORD}';
HERE
)

echo "${SQL}"
