const fs = require('fs');
const p = require('path');

try {
  stats = fs.lstatSync('./.git');

  if (!stats.isDirectory()) {
    // noinspection ExceptionCaughtLocallyJS
    throw 'nope';
  }
}
catch {
  console.error("No .git directory found; run in your repository root.");
  process.exit(-1);
}

const packageJsonFiles = [];

function readdirRecursiveSync(path, cb) {
  const files = fs.readdirSync(path);
  let stats;

  for (const file of files) {
    stats = fs.lstatSync(p.join(path, file));
    if (stats.isDirectory()) {
      if (file !== 'node_modules') {
        readdirRecursiveSync(p.join(path, file), cb);
      }
    } else {
      cb(p.join(path, file));
    }
  }
}


readdirRecursiveSync('.', (file) => {
  if (file.endsWith('/package.json')) {
    packageJsonFiles.push(file);
  }
});


const config = `
# generated by ./github/dependabot.js
# DO NOT EDIT!

version: 2
updates:
` + packageJsonFiles.map(
  pkg => `  - package-ecosystem: "npm"
    directory: "${p.dirname(pkg)}"
    schedule:
      interval: "daily"
`).join('');

console.log("writing .github/dependabot.yml");
fs.writeFileSync(".github/dependabot.yml", config);
process.exit(0);
