#!/bin/bash
echo "creating users"
./data/user.sh | psql -X -e -d ${DB_SUPER_URL} --echo-all -f -

echo "dropping db"
echo "drop database ${PROJECT_NAME} WITH (FORCE);" | psql -X -e -d ${DB_SUPER_URL}
echo "creating db"
echo "create database ${PROJECT_NAME};" | psql -X -e -d ${DB_SUPER_URL}

echo "dropping test db"
echo "drop database ${PROJECT_NAME}_test WITH (FORCE);" | psql -X -e -d ${DB_SUPER_URL}
echo "creating test db"
echo "create database ${PROJECT_NAME}_test;" | psql -X -e -d ${DB_SUPER_URL}

echo $(cat << HERE
grant connect on database hubdb to udba;
grant connect on database hubdb to uclient;
grant connect on database hubdb to ustaff;
grant connect on database hubdb_test to udba;
grant connect on database hubdb_test to uclient;
grant connect on database hubdb_test to ustaff;
HERE
) | psql -X -e -d ${DB_SUPER_URL} -f -

psql -X -e -d ${DB_SUPER_URL}${PROJECT_NAME} --echo-all -f ./data/create_schema_dbuser_permission.sql
psql -X -e -d ${DB_SUPER_URL}${PROJECT_NAME}_test --echo-all -f ./data/create_schema_dbuser_permission.sql

echo "seed ${DB_DBA_URL} [DEV]"
psql -X -e -d ${DB_DBA_URL} --echo-all -f ./data/seed.sql | grep ERROR

echo "seed ${DB_DBA_URL} [TEST]"
psql -X -e -d ${DB_DBA_URL_TEST} --echo-all -f ./data/seed.sql | grep ERROR
