#!/bin/bash
SQL=$(cat <<HERE
CREATE USER udba SUPERUSER PASSWORD '${DB_HELLO_DBA_PASSWORD}';
CREATE USER uclient PASSWORD '${DB_HELLO_CLIENT_PASSWORD}';
CREATE USER ustaff PASSWORD '${DB_HELLO_STAFF_PASSWORD}';
HERE
)

echo "${SQL}"
