#!/usr/bin/env bash
pushd ../../../../lib/ts_agnostic
./build
popd
pushd ../../../../lib/node_core
./build
popd
pushd ../../../../lib/node_script
./build
popd
. ./config/dev_env.sh
PORT=$(cat .port) yarn dev
