#!/usr/bin/env bash
pushd ../../../../lib/ts_agnostic
./build
popd
pushd ../../../../lib/ts_browser
./build
popd
pushd ../../../../lib/vue_workflow
./build
popd
pushd ../../../../lib/vue_workflow_components
./build
popd
if [ -e dist ]
then
  rm -rf dist
fi
yarn build
